// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	models "github.com/IlyushaZ/parser/models"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCa3fdb35DecodeGithubComIlyushaZParserHandlers(in *jlexer.Lexer, out *newsArr) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(newsArr, 0, 1)
			} else {
				*out = newsArr{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 models.News
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCa3fdb35EncodeGithubComIlyushaZParserHandlers(out *jwriter.Writer, in newsArr) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v newsArr) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCa3fdb35EncodeGithubComIlyushaZParserHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v newsArr) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCa3fdb35EncodeGithubComIlyushaZParserHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *newsArr) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCa3fdb35DecodeGithubComIlyushaZParserHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *newsArr) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCa3fdb35DecodeGithubComIlyushaZParserHandlers(l, v)
}
