// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson36e4e286DecodeGithubComIlyushaZParserHandlers(in *jlexer.Lexer, out *body) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "main_url":
			out.MainURL = string(in.String())
		case "url_pattern":
			out.URLPattern = string(in.String())
		case "title_pattern":
			out.TitlePattern = string(in.String())
		case "text_pattern":
			out.TextPattern = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson36e4e286EncodeGithubComIlyushaZParserHandlers(out *jwriter.Writer, in body) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"main_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.MainURL))
	}
	{
		const prefix string = ",\"url_pattern\":"
		out.RawString(prefix)
		out.String(string(in.URLPattern))
	}
	{
		const prefix string = ",\"title_pattern\":"
		out.RawString(prefix)
		out.String(string(in.TitlePattern))
	}
	{
		const prefix string = ",\"text_pattern\":"
		out.RawString(prefix)
		out.String(string(in.TextPattern))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v body) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson36e4e286EncodeGithubComIlyushaZParserHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v body) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson36e4e286EncodeGithubComIlyushaZParserHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *body) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson36e4e286DecodeGithubComIlyushaZParserHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *body) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson36e4e286DecodeGithubComIlyushaZParserHandlers(l, v)
}
